---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 12.6.0
  customize:
    natdnshostresolver1: "on"
    memory: 2048
    natpf1: "jenkins,tcp,127.0.0.1,8080,,8080"
provisioner: chef_zero

platforms:
- name: ubuntu-14.04
  driver_config:
    box: opscode_ubuntu-14.04_chef-provisionerless
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box

suites:
  - name: default
    run_list: "recipe[optoro_ruby]"
    attributes:
      optoro_ruby:
        ruby_major_version: 2.1
        ruby_minor_version: 2
        source_sha256_sum: f22a6447811a81f3c808d1c2a5ce3b5f5f0955c68c9a749182feb425589e6635
  - name: build_package
    run_list: "recipe[optoro_ruby]"
    attributes:
      optoro_ruby:
        install_method: build_package
        ruby_major_version: 2.0
        ruby_minor_version: 0-p481
  - name: install_repo
    run_list: recipe[optoro_ruby]
    data_bags_path: test/data_bags
    encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
    attributes:
      optoro_ruby:
        install_method: install_repo
        ruby_major_version: 2.1
  - name: install_package
    run_list: "recipe[optoro_ruby]"
    data_bags_path: 'test/data_bags'
    encrypted_data_bag_secret_key_path: 'test/integration/encrypted_data_bag_secret'
    attributes:
      optoro_ruby:
        install_method: install_package
        ruby_major_version: 2.1
        ruby_minor_version: 2
  - name: install_rvm
    run_list: "recipe[optoro_ruby]"
    data_bags_path: 'test/data_bags'
    encrypted_data_bag_secret_key_path: 'test/integration/encrypted_data_bag_secret'
    attributes:
      optoro_ruby:
        install_method: rvm
      rvm:
        global_gems:
          - name:
              bundler
          - name:
              rake
        default_ruby: ruby-2.1.5
